version: '3.9'

services:
  web:
    build: 
      context: ../
      dockerfile: ./compose/local/Dockerfile
    container_name: django_app
    command: >
      sh -c " python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../app:/app
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
    env_file:
      - .env/.env
      - .env/.db_env
    restart: always

#   db:
#     image: postgres:15
#     container_name: postgres_db
#     restart: always
#     env_file:
#       - .env/.db_env
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
